openapi: 3.0.0
info:
  title: MultiAuthHelloWorldAPI
  version: 1.0.0
servers:
  - url: https://your-localtunnel-url.localtunnel.me
    description: LocalTunnel development server
paths:
  /noauth:
    get:
      operationId: getNoAuthHello
      summary: Returns a hello message without authentication
      responses:
        '200':
          description: Hello message for no auth endpoint
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /oauth:
    get:
      operationId: getOAuthHello
      summary: Returns a hello message with OAuth authentication
      security:
        - oauth: []
      responses:
        '200':
          description: Hello message for OAuth endpoint
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /serviceauth:
    get:
      operationId: getServiceAuthHello
      summary: Returns a hello message with service level authentication
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: Hello message for service auth endpoint
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        password:
          tokenUrl: https://github.com/login/oauth/access_token
          scopes: {}
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
