openapi: 3.0.0
info:
  title: OAuthHelloWorldAPI
  version: 1.0.0
servers:
  - url: https://your-localtunnel-url.localtunnel.me
    description: LocalTunnel development server
paths:
  /hello:
    get:
      operationId: getHelloWorld
      summary: Returns a 'Hello World' message, requires OAuth token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A simple hello message
          content:
            application/json:
              schema
