TEXT = [
    "This restaurant is awesome",
    "This restaurant is awful",
    "I had a fantastic day at the park",
    "I am so bored with this movie",
    "The book was captivating and insightful",
    "Their customer service is terrible",
    "I absolutely love my new phone",
    "The weather today is dreadful",
    "I'm feeling very hopeful about the future",
    "That was the worst meal I've ever had",
    "I'm indifferent about the new policy",
    "The concert was an amazing experience",
    "I'm frustrated with the internet connection",
    "This is the best vacation I've ever had",
    "I'm worried about the test results",
    "The traffic today was surprisingly light",
    "I'm disappointed with the game's finale",
    "The garden looks beautiful in spring",
    "I feel very uneasy about this decision",
    "The team played brilliantly last night",
]
